### ISSUE TITLE
this.viteServer.on is not a function

### ISSUE THREAD

**Issue by jhonyjss** [xland/vitetron#2]
Hello I tried to start my project with yarn start, but I got an error.

```
this.viteServer.on is not a function
```
red underline is because I am using eslint
![image](https://user-images.githubusercontent.com/25466752/110217148-4e109780-7e91-11eb-9a2c-0fb8c57ad449.png)

**Comment by Pmca96** [comment]
When i run "npm run start" i am able to view the application and test it.
Once i try to make the release, install and execute i have the same error and the application crashes.
Basicly only can run in dev mode.

**Comment by xland** [comment]
@jhonyjss @Pmca96 

This project is archived.
I have no time to maintain it.
